name: nx_commerce
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#----------------- PACKAGES --------------------#
dependencies:
  flutter:
    sdk: flutter

 # Utility Packages
  logger: ^2.3.0
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  lottie: ^3.1.2
  connectivity_plus: ^5.0.1
  shimmer: ^3.0.0

 # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6


  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1


  # Product Specific
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1



  # Firebase
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1
  firebase_storage: ^11.5.4




#----------------- ./ PACKAGES END --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  

  # -------------- LOCAL ASSETS ----------------#
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/images/products/banners/
    - assets/images/products/
    - assets/icons/
    - assets/images/user/
    - assets/icons/brands/
    - assets/images/reviews/
    - assets/icons/payment_methods/
    - assets/icons/successful_payment/

  # -------------- LOCAL FONTS ----------------#
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Thin.ttf
          weight: 100
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LexendDeca-Black.ttf
          weight: 900
