// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA48aoVI4TGUs-tBEsPdbkB5FbqCoVStR8',
    appId: '1:70961405327:android:270b6b4bb8df01dacdbffa',
    messagingSenderId: '70961405327',
    projectId: 'nxcommerce-9d467',
    storageBucket: 'nxcommerce-9d467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqE7UkLI0QRcR4RUdC9QjHGtG11EvDr8',
    appId: '1:70961405327:ios:52eac4fac2269e9ccdbffa',
    messagingSenderId: '70961405327',
    projectId: 'nxcommerce-9d467',
    storageBucket: 'nxcommerce-9d467.appspot.com',
    androidClientId: '70961405327-qdollt1gmp9pgp0ntc1co0cg4p17qh7p.apps.googleusercontent.com',
    iosClientId: '70961405327-2e0b4apl34h1q6uat4bm3u4s6bsqjr26.apps.googleusercontent.com',
    iosBundleId: 'com.example.nxCommerce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0-mCr-O5iN7JO3B-8jH0ogcIl6wNh0o',
    appId: '1:70961405327:web:8b5b174fce1d7251cdbffa',
    messagingSenderId: '70961405327',
    projectId: 'nxcommerce-9d467',
    authDomain: 'nxcommerce-9d467.firebaseapp.com',
    storageBucket: 'nxcommerce-9d467.appspot.com',
    measurementId: 'G-0NZCSDVFNS',
  );

}